export const foods = [
    {
      id: 1,
      name: 'Caesar Salad',
      href: '#',
      price: '300',
      imageSrc: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
      imageAlt: 'Bowl of Caesar salad with lettuce, croutons, and cheese.',
    },
    // {
    //   id: 2,
    //   name: 'Strawberry Ice Cream',
    //   href: '#',
    //   price: '$8',
    //   imageSrc: 'https://images.pexels.com/photos/818874/pexels-photo-818874.jpeg',
    //   imageAlt: 'Scoops of strawberry ice cream in a bowl.',
    // }
    ,
    {
      id: 3,
      name: 'Chocolate Cake',
      href: '#',
      price: '1500',
      imageSrc: 'https://images.pexels.com/photos/4110005/pexels-photo-4110005.jpeg',
      imageAlt: 'Chocolate cake topped with chocolate shavings.',
    },
    {
      id: 4,
      name: 'Spaghetti Noodles',
      href: '#',
      price: '2000',
      imageSrc: 'https://images.pexels.com/photos/64208/pexels-photo-64208.jpeg',
      imageAlt: 'Spaghetti noodles with tomato sauce and basil.',
    },
    // {
    //   id: 5,
    //   name: 'Orange Juice',
    //   href: '#',
    //   price: '$5',
    //   imageSrc: 'https://images.pexels.com/photos/112867/pexels-photo-112867.jpeg',
    //   imageAlt: 'Glass of fresh orange juice with a slice of orange.',
    // }
    // ,
    // {
    //   id: 6,
    //   name: 'Veg Roll',
    //   href: '#',
    //   price: '$7',
    //   imageSrc: 'https://images.pexels.com/photos/3627302/pexels-photo-3627302.jpeg',
    //   imageAlt: 'Veg roll with fresh vegetables inside a flatbread.',
    // }
    // ,
    {
      id: 7,
      name: 'Greek Salad',
      href: '#',
      price: '2000',
      imageSrc: 'https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg',
      imageAlt: 'Greek salad with tomatoes, cucumbers, olives, and feta cheese.',
    },
    // {
    //   id: 8,
    //   name: 'Vanilla Ice Cream',
    //   href: '#',
    //   price: '$8',
    //   imageSrc: 'https://images.pexels.com/photos/346945/pexels-photo-346945.jpeg',
    //   imageAlt: 'Vanilla ice cream in a bowl with a spoon.',
    // },
    {
      id: 9,
      name: 'Red Velvet Cake',
      href: '#',
      price: '1800',
      imageSrc: 'https://images.pexels.com/photos/3026808/pexels-photo-3026808.jpeg',
      imageAlt: 'Slice of red velvet cake with cream cheese frosting.',
    },
    // {
    //   id: 10,
    //   name: 'Chow Mein',
    //   href: '#',
    //   price: '$14',
    //   imageSrc: 'https://images.pexels.com/photos/2630702/pexels-photo-2630702.jpeg',
    //   imageAlt: 'Chow mein noodles with vegetables and soy sauce.',
    // },
    {
      id: 11,
      name: 'Mango Juice',
      href: '#',
      price: '900',
      imageSrc: 'https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg',
      imageAlt: 'Glass of mango juice with a mango slice on the rim.',
    },
    // {
    //   id: 12,
    //   name: 'Spring Roll',
    //   href: '#',
    //   price: '$9',
    //   imageSrc: 'https://images.pexels.com/photos/1024438/pexels-photo-1024438.jpeg',
    //   imageAlt: 'Spring rolls with dipping sauce on the side.',
    // },
    {
      id: 13,
      name: 'Fruit Salad',
      href: '#',
      price: '3500',
      imageSrc: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg',
      imageAlt: 'Fruit salad with various fresh fruits in a bowl.',
    },
    // {
    //   id: 14,
    //   name: 'Mint Chocolate Ice Cream',
    //   href: '#',
    //   price: '$9',
    //   imageSrc: 'https://images.pexels.com/photos/1343502/pexels-photo-1343502.jpeg',
    //   imageAlt: 'Mint chocolate chip ice cream in a cone.',
    // },
    // {
    //   id: 15,
    //   name: 'Carrot Cake',
    //   href: '#',
    //   price: '$16',
    //   imageSrc: 'https://images.pexels.com/photos/57943/pexels-photo-57943.jpeg',
    //   imageAlt: 'Slice of carrot cake with cream cheese frosting.',
    // },
    // {
    //   id: 16,
    //   name: 'Udon Noodles',
    //   href: '#',
    //   price: '$12',
    //   imageSrc: 'https://images.pexels.com/photos/688776/pexels-photo-688776.jpeg',
    //   imageAlt: 'Udon noodles in a broth with green onions and egg.',
    // },
    // {
    //   id: 17,
    //   name: 'Lemonade',
    //   href: '#',
    //   price: '$5',
    //   imageSrc: 'https://images.pexels.com/photos/1264184/pexels-photo-1264184.jpeg',
    //   imageAlt: 'Glass of lemonade with lemon slices and mint leaves.',
    // },
    {
      id: 18,
      name: 'Veggie Wrap',
      href: '#',
      price: '5000',
      imageSrc: 'https://images.pexels.com/photos/1600713/pexels-photo-1600713.jpeg',
      imageAlt: 'Veggie wrap with fresh vegetables and hummus.',
    },
    {
      id: 19,
      name: 'Caprese Salad',
      href: '#',
      price: '1240',
      imageSrc: 'https://images.pexels.com/photos/853006/pexels-photo-853006.jpeg',
      imageAlt: 'Caprese salad with tomatoes, mozzarella, and basil.',
    },
    // {
    //   id: 20,
    //   name: 'Chocolate Sundae',
    //   href: '#',
    //   price: '$10',
    //   imageSrc: 'https://images.pexels.com/photos/1452460/pexels-photo-1452460.jpeg',
    //   imageAlt: 'Chocolate sundae with whipped cream and a cherry on top.',
    // }
  ];
  